[Greeting]
hash = "sha1-5b49bfdad81fedaeefb224b0ffc2acc58b09cff5"
other = "你好，{{.Name}}"

[UnreadEmails]
description = "The number of unread emails I have"
hash = "sha1-6a65d17f53981a3657db1897630e9cb069053ea8"
other = "您有 {{.PluralCount}} 份未读邮件."

[UnreadSMS]
description = "The number of unread emails I have"
hash = "sha1-c9b6479a0fae2d8d73bffd12acc7f3756e9a74b6"
other = "您有{{.PluralCount}}份未读短信."

[ERR_Auth]
description = "授权验证失败"
hash = "sha1-452fff353b99415855701bf64be8b3718babd604"
other = "授权验证失败"

[ERR_DB]
description = "数据库错误"
hash = "sha1-bc46ad6c66d574603d3f70221bcc9fa12999c72a"
other = "数据库错误"

[ERR_Server]
description = "服务错误"
hash = "sha1-979c68301379820faea89e41d9b71576c01ba7be"
other = "服务错误"

