[ERR_Auth]
description = "授权验证失败"
hash = "sha1-452fff353b99415855701bf64be8b3718babd604"
other = "auth error"

[ERR_DB]
description = "数据库错误"
hash = "sha1-bc46ad6c66d574603d3f70221bcc9fa12999c72a"
other = "Database error"

[ERR_Server]
description = "服务错误"
hash = "sha1-979c68301379820faea89e41d9b71576c01ba7be"
other = "server error"
